# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66cded139c0f7236464f8203fbef4fcca2ef69e0d34768a08226f1afc6d944b79d1d704d283d8b2954a0587d37809afcc736ea89fe6c216223e841d5e8145958

test:
  secret_key_base: d7b45e2b7a05df59247ee2e4cafcf086b4a1195f2fd8b26ec6d78f8db908ed982e75cb763684eb3086782264efeac04a24ea3595fa7a69c3e7ed961cba083d10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
